LinearRegression

In [1]:
# importing necessary packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)
%matplotlib inline

In [2]:
data = pd.read_csv("for_model.csv")

In [3]:
data

Unnamed: 0  room_bed  room_bath  living_measure  ceil  coast  sight  \
0               0         4       3.25            3020   1.0      0      0   
1               1         4       2.50            2550   1.0      0      0   
2               2         3       2.50            2370   2.0      0      0   
3               3         2       1.00             820   1.0      0      0   
4               4         2       1.50            1400   1.0      0      0   
...           ...       ...        ...             ...   ...    ...    ...   
21420       21608         4       2.50            2303   2.0      0      0   
21421       21609         4       2.50            3490   2.0      0      0   
21422       21610         4       2.75            2790   2.0      0      0   
21423       21611         2       2.00            1440   1.0      0      0   
21424       21612         3       1.00             970   1.5      0      0   

       condition  quality  ceil_measure  basement  yr_renovated  \
0              5        9          3020         0             0   
1              3        8          1750       800             0   
2              3        8          2370         0             0   
3              4        6           820         0             0   
4              4        8          1400         0             0   
...          ...      ...           ...       ...           ...   
21420          3        8          2303         0             0   
21421          3        8          3490         0             0   
21422          3        8          2790         0             0   
21423          3        7          1440         0             0   
21424          3        7           970         0             0   

       living_measure15  furnished  total_area   price  
0                  2120          1       16477  808100  
1                  2260          0       10050  277500  
2                  2370          0        6694  404000  
3                  1520          0        4664  300000  
4                  1900          0        5450  699000  
...                 ...        ...         ...     ...  
21420              2516          0        6129  300000  
21421              2910          0        8490  320000  
21422              2620          0        8317  483453  
21423              1780          0       16440  365000  
21424              1730          0        6892  354950  

[21425 rows x 16 columns]

In [4]:
data = data.drop(data.columns[[0]], axis=1)

In [5]:
data.columns

Index(['room_bed', 'room_bath', 'living_measure', 'ceil', 'coast', 'sight',
       'condition', 'quality', 'ceil_measure', 'basement', 'yr_renovated',
       'living_measure15', 'furnished', 'total_area', 'price'],
      dtype='object')

In [6]:
#train test split

from sklearn.model_selection import train_test_split

X = data.drop('price',axis=1)     
y = data['price']   

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)

X1,X2 = (len(X_train)),(len(X_test))
y1,y2 = (len(y_train)),(len(y_test))

print ("Train values :" +  " " + str(X1) + " " + str(X2))
print ("Test values :" +  " " + str(y1) + " " + str(y2))

Train values : 19282 2143
Test values : 19282 2143


In [7]:
#validation

X_val_train, cv_X_test, y_val_train, cv_y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=1)

X3,X4 = (len(X_val_train)),(len(cv_X_test))
y3,y4 = (len(y_val_train)),(len(cv_y_test))

print ("Train values :" +  " " + str(X3) + " " + str(X4))
print ("Test values :" +  " " + str(y3) + " " + str(y4))

Train values : 15425 3857
Test values : 15425 3857


In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
# fit scaler on training data
norm = MinMaxScaler().fit(X_val_train)

# transform training data
X_val_train_norm = norm.transform(X_val_train)

# transform testing dataabs
cv_X_test_norm = norm.transform(cv_X_test)

In [10]:
print(X_val_train_norm)

[[0.375      0.28125    0.12328767 ... 0.22732748 0.         0.00750165]
 [0.625      0.4375     0.18005137 ... 0.28239546 0.         0.00625713]
 [0.625      0.375      0.25428082 ... 0.49750473 1.         0.00769908]
 ...
 [0.375      0.3125     0.10958904 ... 0.26518671 0.         0.00864867]
 [0.375      0.3125     0.26712329 ... 0.23076923 0.         0.00876737]
 [0.25       0.09375    0.06506849 ... 0.19807262 0.         0.00674404]]


### Linear

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lr_model = LinearRegression()
lr_model.fit(X_val_train_norm, y_val_train)
lr_predict = lr_model.predict(cv_X_test_norm)

In [13]:
lr_model.score(X_val_train_norm, y_val_train)

0.6099204804898164

In [14]:
lr_model.score(cv_X_test_norm, cv_y_test)

0.6086903360808502

### Polynomial 

In [15]:
from sklearn.preprocessing import PolynomialFeatures

In [16]:
poly = PolynomialFeatures(degree=2, interaction_only=True)

In [17]:
X_poly = poly.fit_transform(X_train)
poly_X_train, poly_X_test, poly_y_train, poly_y_test = train_test_split(X_poly, y_train, test_size=0.20, random_state=1)
X_train.shape

(19282, 14)

In [18]:
poly_lr_model = lr_model.fit(poly_X_train, poly_y_train)
poly_lr_predict = poly_lr_model.predict(poly_X_test)

In [19]:
poly_lr_model.score(poly_X_train, poly_y_train)

0.7137956740964677

In [20]:
poly_lr_model.score(poly_X_test, poly_y_test)

0.6825053456826017

### Lasso

In [21]:
from sklearn.linear_model import ridge_regression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [22]:
ridge_model = Ridge(alpha=.3)
ridge_model.fit(X_val_train_norm, y_val_train)
print ("Ridge model:", (ridge_model.coef_))

Ridge model: [-298239.98094693  -68057.49637081  875088.30392232  -15819.97614422
  530020.62475291  228385.85705693  227969.21980788  944979.50912085
  850768.246307    621993.56404028  141981.20134646   81420.71292384
   48988.06226425 -562586.45985223]


In [23]:
print(ridge_model.score(X_val_train_norm, y_val_train))
print(ridge_model.score(cv_X_test_norm, cv_y_test))

0.6099164343583502
0.6088065764773003


In [24]:
from sklearn.linear_model import Lasso

In [25]:
lasso_model = Lasso(alpha=1.0)
lasso_model.fit(X_val_train_norm, y_val_train)
print ("Ridge model:", (lasso_model.coef_))

Ridge model: [-300952.66841421  -72823.20743966 3029168.75954958  -16188.47250971
  531185.40179882  228007.79944464  227994.59127131  948812.68902158
 -704075.94344807 -261689.82374287  141873.29018748   77792.78979282
   47913.77876664 -581615.35633862]


C:\Users\Sri Lekha\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 185677583369293.94, tolerance: 211538026722.80203
  positive)


In [26]:
print(lasso_model.score(X_val_train_norm, y_val_train))
print(lasso_model.score(cv_X_test_norm, cv_y_test))

0.6099204559010216
0.6086872850672784


### Decision Tree Regressor

In [27]:
from sklearn.tree import DecisionTreeRegressor

In [28]:
DT1_model = DecisionTreeRegressor()
DT1_model.fit(X_val_train_norm , y_val_train)
y_pred = DT1_model.predict(cv_X_test_norm)

In [29]:
print(DT1_model.score(X_val_train_norm, y_val_train))
print(DT1_model.score(cv_X_test_norm, cv_y_test ))

0.9999963673661322
0.3874152990196691


### Gradient boosting regressor, Random forest regressor

In [32]:
from scipy.stats import zscore
#importing the metrics
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [33]:
from sklearn.ensemble import (RandomForestRegressor, GradientBoostingRegressor)
model_gbr=GradientBoostingRegressor()
model_gbr.fit(X_val_train_norm, y_val_train)

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [34]:
y_pred = model_gbr.predict(cv_X_test_norm)
print(type(cv_X_test_norm))
#Evaluate the model using accuracy
acc_GB=r2_score(cv_y_test, y_pred)
print('Accuracy DT: ',acc_GB)
print('MSE: ',mean_squared_error(cv_y_test, y_pred))

<class 'numpy.ndarray'>
Accuracy DT:  0.6834143534997109
MSE:  36138124568.48613


In [35]:
print(model_gbr.score(X_val_train_norm, y_val_train))
print(model_gbr.score(cv_X_test_norm, cv_y_test))

0.7669498234132989
0.6834143534997109


#****************************************************#

In [36]:
model_rfr=RandomForestRegressor(n_estimators=50)
model_rfr.fit(X_val_train_norm, y_val_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=50, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [37]:
y_pred = model_rfr.predict(cv_X_test_norm)
print(type(cv_X_test_norm))
#Evaluate the model using accuracy
acc_RF=r2_score(cv_y_test, y_pred)
print('Accuracy DT: ',acc_RF)
print('MSE: ',mean_squared_error(cv_y_test, y_pred))

<class 'numpy.ndarray'>
Accuracy DT:  0.6768711238521532
MSE:  36885031608.327034


In [38]:
print(model_rfr.score(X_val_train_norm, y_val_train))
print(model_rfr.score(cv_X_test_norm, cv_y_test))

0.9592589091417854
0.6768711238521532
